live_config_reload = true

# other nice themes: gotham
import = [
    # "~/.config/alacritty/my_theme.toml"
    # "~/.config/alacritty/themes/themes/tokyo-night.toml"
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[window]
startup_mode = "Maximized"
decorations = "None"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
    # alt+t swaps last 2 args in command
    { key = "t", mods = "Alt", action = "None" },
]

[cursor]
style = { shape="Beam", blinking="On" }

[selection]
save_to_clipboard = true
