theme = "sonokai"

# [editor.statusline]
# left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
# center = []
# right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

# refer: https://github.com/LGUG2Z/helix-vim/blob/master/config.toml

[keys.normal]
# Quick iteration on config changes
C-r = ":config-reload"
# easy save
C-s = ":write"

# Some nice Helix stuff
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = ["goto_next_paragraph", "collapse_selection"]
C-k = ["goto_prev_paragraph", "collapse_selection"]

# "{" = ["goto_prev_paragraph", "collapse_selection"]
# "}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"L" = "goto_line_end"
"H" = "goto_first_nonwhitespace"
G = "goto_file_end"
# "%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
S = "surround_add" 

# x = "delete_selection"
# p = ["paste_clipboard_after", "collapse_selection"]
# P = ["paste_clipboard_before", "collapse_selection"]
# Y = ["extend_to_line_end", "yank_main_selection_to_clipboard", "collapse_selection"]

# this one is essential
esc = ["collapse_selection", "keep_primary_selection"]

# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

[keys.normal.space]
"space" = "goto_last_accessed_file"
# "H" = ":toggle lsp.display-inlay-hints"

[keys.insert]
j = { j = "normal_mode" }
esc = ["collapse_selection", "normal_mode"]

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"L" = "goto_line_end"
"H" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
S = "surround_add"
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

# y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
# Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
# p = "replace_selections_with_clipboard"
# P = "paste_clipboard_before"

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

C-j = ["goto_next_paragraph"]
C-k = ["goto_prev_paragraph"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
