theme = "poimandres"

[editor]
bufferline = "multiple"

[editor.smart-tab]
enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false

# refer: https://github.com/LGUG2Z/helix-vim/blob/master/config.toml

[keys.normal]
ret = "command_mode"
C-r = ":config-reload"
C-s = ":write"

# Some nice Helix stuff
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = ["goto_next_paragraph", "collapse_selection"]
C-k = ["goto_prev_paragraph", "collapse_selection"]

0 = "goto_line_start"
"L" = "goto_line_end"
"H" = "goto_first_nonwhitespace"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]

Y = ["extend_to_line_end", "yank_main_selection_to_clipboard", "collapse_selection"]

# this one is essential
esc = ["collapse_selection", "keep_primary_selection"]

# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

[keys.normal.space]
"space" = "goto_last_accessed_file"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"L" = "goto_line_end"
"H" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

C-j = ["goto_next_paragraph"]
C-k = ["goto_prev_paragraph"]

