# https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#python---pyright
[[language]]
name = "python"
language-servers = [ "pyright" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]
