# model: ollama:llama3
# model: groq:llama3-70b-8192
model: openai:gpt-4o-mini
clients:
- type: openai
  api_key: $OPENAIKEY
  api_base: https://api.openai.com/v1
- type: openai-compatible
  name: groq
  api_base: https://api.groq.com/openai/v1
  api_key: $GROQKEY
- type: ollama
  api_base: http://localhost:11434
  api_auth: Basic xxx
  models:
    - name: llama3
      max_input_tokens: 8192
